[theme]
# "light" or "dark".
base = "light"

# primary accent color for interactive elements
primaryColor = "#6eaff0ff"

# Background color for the main content area.
backgroundColor = "#f0f4f4ff"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "lightgray"

# Color used for almost all text.
textColor = "#262730"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
font = "sans serif"

[runner]
enforceSerializableSessionState = true